// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagination.WebApi.Contexts;

namespace Pagination.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220217124344_BondMigration")]
    partial class BondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pagination.WebApi.Models.BondAppData", b =>
                {
                    b.Property<int>("BondApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BondCompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BondType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentAuthorizedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentCapturedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BondApplicationID");

                    b.ToTable("BondAppDatas");
                });

            modelBuilder.Entity("Pagination.WebApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
